---
# This playbook contains CS private provision steps that are run on the vagrant VM.
- name: Provision
  become: yes
  become_user: "{{ user }}"
  hosts:
    - "{{ hosts }}"
    - all
  vars:
    user: 'vagrant'
    hosts: 'localhost'
    _github_oauth_token: '{{ github_oauth_token }}'

  pre_tasks:
    - name: Gathering facts
      setup:

  environment:
    GITHUB_OAUTH_TOKEN: "{{ github_oauth_token }}"

  tasks:
    - name: Copy .bashrc file
      template:
        src: templates/bashrc.j2
        dest: '/home/{{ user }}/.bashrc'
        owner: '{{ user }}'
        mode: '0644'
      tags: bashrc

    - name: Create .aws directory if it does not exist
      file:
        path: /home/{{ user }}/.aws
        state: directory
        mode: '0755'
      tags: awsconfig

    - name: Add aws config file
      copy:
        src: files/aws-config
        dest: '/home/{{ user }}/.aws/config'
        mode: 0644
      tags: awsconfig

    - name: Create ~/code directory if it does not exist
      file:
        path: /home/{{ user }}/code
        state: directory
        mode: '0755'
      tags: codedir
    - name: Add the pgadmin4 repository key
      become: true
      shell: >
        curl https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo apt-key add
      tags: pgadmin
    - name: Install pgadmin4 repository source
      become: true
      become_user: root
      shell: >
        echo "deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list
        && apt update
      tags: pgadmin
    - name: Install pgadmin4 web version
      become: true
      become_user: root
      apt:
        name: pgadmin4-web
        update_cache: 'yes'
      tags: pgadmin
    - name: Create ~/.pgadmin directory for the pgAdmin web tool. It's an IDE for psql databases
      file:
        path: '/home/{{ user }}/.pgadmin'
        state: directory
        mode: '0755'
      tags: pgadmin

    - name: Copy pgadmin4.db file to ~/.pgadmin
      copy:
        src: files/pgadmin4.db
        dest: '/home/{{ user }}/.pgadmin'
        owner: '{{ user }}'
        mode: '0644'
        force: no
      tags: pgadmin

    - name: Set fs.inotify.max_user_watches to 524288 in /etc/sysctl.conf
      sysctl:
        name: fs.inotify.max_user_watches
        value: '524288'
        state: present
      become: true
      become_user: root
      tags: inotify





