---
# This playbook contains CS private provision steps that are run on the vagrant VM.
- name: Provision
  become: yes
  become_user: "{{ user }}"
  hosts:
    - "{{ hosts }}"
    - all
  vars:
    user: 'vagrant'
    hosts: 'localhost'
    _github_oauth_token: '{{ github_oauth_token }}'

  pre_tasks:
    - name: Gathering facts
      setup:

  environment:
    GITHUB_OAUTH_TOKEN: "{{ github_oauth_token }}"

  tasks:
    - name: Copy .bashrc file
      template:
        src: templates/bashrc.j2
        dest: '/home/{{ user }}/.bashrc'
        owner: '{{ user }}'
        mode: '0644'
      tags: bashrc

    - name: Create .aws directory if it does not exist
      file:
        path: /home/{{ user }}/.aws
        state: directory
        mode: '0755'
      tags: awsconfig

    - name: Add aws config file
      copy:
        src: files/aws-config
        dest: '/home/{{ user }}/.aws/config'
        mode: 0644
      tags: awsconfig

    - name: Copy pgadmin4.db file to ~/.pgadmin
      copy:
        src: files/pgadmin4.db
        dest: '/home/{{ user }}/.pgadmin'
        owner: '{{ user }}'
        mode: '0644'
        force: no
      tags: pgadmin

    - name: Set fs.inotify.max_user_watches to 524288 in /etc/sysctl.conf
      sysctl:
        name: fs.inotify.max_user_watches
        value: '524288'
        state: present
      become: true
      become_user: root
      tags: inotify





